### ISSUE TITLE
Test Carcel

### ISSUE THREAD

**Issue by diegosanchez** [PedroRodP/TP2-Algos3#11]
```java
    public void test01JugadorAzulEsArrestadoYRecuperaSuLibertad3RondasDespues() throws JugadorJugandoNoTieneMasEstados {
        
    	Jugador jugadorAzul = new Jugador();
    	ArrayList<Jugador> listaJugadores = new ArrayList<>();
        Tablero unTablero = new Tablero();

        listaJugadores.add(jugadorAzul);
        unTablero.agregarJugadores(listaJugadores);

        Carcel laCarcel = unTablero.getCarcel();

        laCarcel.arrestar(jugadorAzul);

        Assert.assertEquals(1,laCarcel.cantidadDePresos());

        laCarcel.cumplirRonda();
        laCarcel.cumplirRonda();
        laCarcel.cumplirRonda();

        Assert.assertEquals(0,laCarcel.cantidadDePresos());
    }
```

Este test no tiene sentido, desde el punto de vista funcional.  Lo que necesitamos probar cuando un jugador cae en la cárcel es:
- No se puede mover el jugador.
- No puede pagar la fianza antes de n turnos.
- Cuando paga fianza puede mover y se descuenta capital.

Pero en ninguno de los casos se prueba que la cantidad de presos sea *n*.

**Comment by NicoCometta** [comment]
Bien Diego, gracias por las observaciones. Estamos viendo cambios en el modelo para poder aplicar pruebas no tan forzadas y a sus vez que se pueda implementar el Patrón Factory
