### ISSUE TITLE
Primera entrega estado

### ISSUE THREAD

**Issue by diegosanchez** [PedroRodP/TP2-Algos3#13]
No encuentro la implementación de algunos casos de uso. 

https://github.com/PedroRodP/TP2-Algos3/pull/12

Es posible?

**Comment by PedroRodP** [comment]
Cuáles casos de uso puntualmente? 
El caso de verificar propietario una vez comprado un barrio en realidad creo que lo confundimos con verificar que el capital se decrementa. Es decir, verificamos capital del jugador, en vez de propietario del barrio. Aún así, en JugadorTest, la prueba 03 verifica que el jugador es el nuevo Propietario de Neuquen (mismo caso de uso).

**Comment by PedroRodP** [comment]
Ya leí el README y vi las pruebas faltantes.
Luciano se encargó de la parte de Avance dinamico y sus pruebas están en JugadorTest. Dijo que el motivo es que se le pedía al jugador que avance determinada cantidad de pasos para caer en el casillero Avance.
Lo mismo para el caso de uso del casillero Policia

**Comment by lucianolop88** [comment]
Faltaban 2/3 tests
