### ISSUE TITLE
AdministradorDeCompra y su responsabilidad

### ISSUE THREAD

**Issue by diegosanchez** [PedroRodP/TP2-Algos3#7]
Porqué la responsabilidad de ```AdministradorDeCompra``` no la tiene el barrio? Q agrega?

**Comment by PedroRodP** [comment]
En realidad se me ocurrió al principio, buscando dividir las responsabilidades de alquiler del terreno de las de compra y venta. Podría encargarse el barrio mismo, pero me parecía mucho código para una misma clase.
