### ISSUE TITLE
AdministradorDeCompras

### ISSUE THREAD

**Issue by diegosanchez** [PedroRodP/TP2-Algos3#9]
```java
	private void setDisponible() {
		
		disponibilidad = new Disponible();
		duenio = null;
	}
	
```

El dueño puede ser null.  No queremos utilizar el null porque no es un objeto.  Como lo podemos reemplazar?

**Comment by PedroRodP** [comment]
Lo discutimos con Nico C en su momento y se nos ocurrió crear una interfaz Propietario. Jugador y SinPropietario implementan esta interfaz. Y ese código queda así:
private void setDisponible() {
		
		disponibilidad = new Disponible();
		duenio = new SinPropietario();
	}
